#!/usr/bin/env tsx
// Generates the component catalogue inside the agent skill (skills/shaders/) from the
// core registry, so the skill never lists a component that doesn't exist:
//   - skills/shaders/components.md   fully generated: every component, one line each
//   - skills/shaders/SKILL.md        the block between the catalog markers is rewritten
// Runs as part of `pnpm lib:build` (scripts/build.ts) and standalone via
// `tsx scripts/generateSkillDocs.ts` once packages/core is built.
import fs from 'fs-extra'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const packageDir = path.resolve(__dirname, '..')
const rootDir = path.resolve(packageDir, '../..')
const skillDir = path.join(rootDir, 'skills/shaders')

const CATALOG_START = '<!-- catalog:start -->'
const CATALOG_END = '<!-- catalog:end -->'

// Display order for categories: what a page is usually built from first.
const CATEGORY_ORDER = [
  'Textures', 'Shapes', 'Shape Effects', 'Blurs', 'Distortions', 'Adjustments',
  'Stylize', 'Interactive', 'Transitions', 'Utilities'
]

interface SkillShader {
  name: string
  category: string
  description: string
  requiresChild: boolean
}

async function loadShaders(): Promise<SkillShader[]> {
  const registryPath = path.join(rootDir, 'packages/core/dist/registry.js')
  if (!await fs.pathExists(registryPath)) {
    throw new Error(`Core registry dist not found at: ${registryPath}. Run 'pnpm run build' in core package first.`)
  }
  const registry = await import(`file://${registryPath}`)
  return registry.getAllShaders().map((shader: any) => ({
    name: shader.name,
    category: shader.category,
    description: String(shader.definition?.description || shader.description || '').replace(/\s+/g, ' ').trim(),
    requiresChild: !!shader.definition?.requiresChild
  }))
}

function groupByCategory(shaders: SkillShader[]): Map<string, SkillShader[]> {
  const groups = new Map<string, SkillShader[]>()
  const order = (c: string) => {
    const i = CATEGORY_ORDER.indexOf(c)
    return i === -1 ? CATEGORY_ORDER.length : i
  }
  const categories = [...new Set(shaders.map(s => s.category))].sort((a, b) => order(a) - order(b) || a.localeCompare(b))
  for (const category of categories) {
    groups.set(category, shaders.filter(s => s.category === category).sort((a, b) => a.name.localeCompare(b.name)))
  }
  return groups
}

function renderCatalog(groups: Map<string, SkillShader[]>, total: number): string {
  const lines = [`${total} components, by category:`, '']
  for (const [category, shaders] of groups) {
    lines.push(`- **${category}** (${shaders.length}): ${shaders.map(s => s.name).join(', ')}`)
  }
  return lines.join('\n')
}

function renderComponents(groups: Map<string, SkillShader[]>, total: number): string {
  const lines = [
    '# Shaders components',
    '',
    '<!-- Generated by packages/shaders/scripts/generateSkillDocs.ts from the shader registry. Do not edit. -->',
    '',
    `Every component in the \`shaders\` package (${total}). "Needs input" marks an effect: it transforms the layers drawn before it (siblings above it, or children nested inside it when it should affect only those). The rest draw on their own.`,
    '',
    'Props, defaults and ranges: `https://shaders.com/docs/components/<Name>` (send `Accept: text/markdown`).',
    ''
  ]
  for (const [category, shaders] of groups) {
    lines.push(`## ${category}`, '')
    for (const s of shaders) {
      const suffix = s.requiresChild ? ' (needs input)' : ''
      lines.push(`- **${s.name}**${suffix}: ${s.description}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

export async function generateSkillDocs(): Promise<number> {
  const shaders = await loadShaders()
  const groups = groupByCategory(shaders)

  await fs.writeFile(path.join(skillDir, 'components.md'), renderComponents(groups, shaders.length))

  const skillPath = path.join(skillDir, 'SKILL.md')
  const skill = await fs.readFile(skillPath, 'utf8')
  const start = skill.indexOf(CATALOG_START)
  const end = skill.indexOf(CATALOG_END)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${skillPath} is missing the ${CATALOG_START} / ${CATALOG_END} markers`)
  }
  const updated = skill.slice(0, start + CATALOG_START.length) + '\n' + renderCatalog(groups, shaders.length) + '\n' + skill.slice(end)
  await fs.writeFile(skillPath, updated)

  console.log(`  ✓ Generated skills/shaders catalogue (${shaders.length} components)`)
  return shaders.length
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generateSkillDocs().catch((error) => {
    console.error('❌ Skill docs generation failed:', error)
    process.exit(1)
  })
}
